apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          env:
            - name: POSTGRES_USER
              value: "postgresadmin"
            - name: POSTGRES_HOST
              value: "192.168.99.100"
            - name: POSTGRES_DB
              value: "postgresdb"
            - name: POSTGRES_PASSWORD
              value: "admin123"
          image: skribblemusic/boone-example-2:v1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080