apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          env:
            - name: PGUSER
              value: "postgresadmin"
            - name: PGHOST
              value: "postgres"
            - name: PGDATABASE
              value: "postgresdb"
            - name: PGPASSWORD
              value: "admin123"
            - name: PGPORT
              value: "5432"
          image: skribblemusic/boone-example-2:release-0.0.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080